apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-store
  namespace: music-store
  labels:
    app: music-store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: music-store
  template:
    metadata:
      labels:
        app: music-store
    spec:
      containers:
        - name: music-store
          image: <aws_account_id>.dkr.ecr.ap-south-1.amazonaws.com/music-store:latest
          ports:
            - containerPort: 8080
    